<?php
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class AuriappSettings {
	private $auriapp_settings_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'auriapp_settings_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'auriapp_settings_page_init' ) );
	}

	public function auriapp_settings_add_plugin_page() {
		add_menu_page(
			'Auriapp Settings', // page_title
			'Auriapp', // menu_title
			'manage_options', // capability
			'auriapp-settings', // menu_slug
			array( $this, 'auriapp_settings_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			80 // position
		);
	}

	public function auriapp_settings_create_admin_page() {
		$this->auriapp_settings_options = get_option( 'auriapp_settings_option_name' ); ?>

		<div class="wrap">
			<h2>Auriapp Settings</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'auriapp_settings_option_group' );
					do_settings_sections( 'auriapp-settings-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function auriapp_settings_page_init() {
		register_setting(
			'auriapp_settings_option_group', // option_group
			'auriapp_settings_option_name', // option_name
			array( $this, 'auriapp_settings_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'auriapp_settings_setting_section', // id
			'Settings', // title
			array( $this, 'auriapp_settings_section_info' ), // callback
			'auriapp-settings-admin' // page
		);

		add_settings_field(
			'testi_0', // id
			'testi', // title
			array( $this, 'testi_0_callback' ), // callback
			'auriapp-settings-admin', // page
			'auriapp_settings_setting_section' // section
		);
	}

	public function auriapp_settings_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['testi_0'] ) ) {
			$sanitary_values['testi_0'] = sanitize_text_field( $input['testi_0'] );
		}

		return $sanitary_values;
	}

	public function auriapp_settings_section_info() {
		
	}

	public function testi_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="auriapp_settings_option_name[testi_0]" id="testi_0" value="%s">',
			isset( $this->auriapp_settings_options['testi_0'] ) ? esc_attr( $this->auriapp_settings_options['testi_0']) : ''
		);
	}

}

if ( is_admin() )
	$auriapp_settings = new AuriappSettings();

/* 
 * Retrieve this value with:
 * $auriapp_settings_options = get_option( 'auriapp_settings_option_name' ); // Array of All Options
 * $testi_0 = $auriapp_settings_options['testi_0']; // testi
 */

