name: Build and Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      # Install dependencies and build the project
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

      - name: Backup old assets on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
            if [ -d "${{ vars.SERVER_PATH }}/dist/" ]; then
              mkdir -p "${{ vars.SERVER_PATH }}/previous/${TIMESTAMP}/"
              mv "${{ vars.SERVER_PATH }}/dist/" "${{ vars.SERVER_PATH }}/previous/${TIMESTAMP}/"
            else
              echo "No dist/ directory to backup."
            fi
      - name: Deploy via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: 'dist/assets/'
          target: '${{ vars.SERVER_PATH }}/dist/assets/'
